// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg3vANrPD1qnbcPopEG-KDHfyIVIsMPZE',
    appId: '1:288094030368:web:8cd006ab39351946494a45',
    messagingSenderId: '288094030368',
    projectId: 'todoapp-3f159',
    authDomain: 'todoapp-3f159.firebaseapp.com',
    storageBucket: 'todoapp-3f159.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtCxqNZMvb8fqwFaoyYXnX4m-4y4Y5REM',
    appId: '1:288094030368:android:d56465e02dab673a494a45',
    messagingSenderId: '288094030368',
    projectId: 'todoapp-3f159',
    storageBucket: 'todoapp-3f159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATtkNomYTtbVW8QmOUNGEYciC_IBeMEiQ',
    appId: '1:288094030368:ios:b57d8337b845b441494a45',
    messagingSenderId: '288094030368',
    projectId: 'todoapp-3f159',
    storageBucket: 'todoapp-3f159.appspot.com',
    iosClientId: '288094030368-mif4ontfvade2e2u5fprqvgpmq1h92cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATtkNomYTtbVW8QmOUNGEYciC_IBeMEiQ',
    appId: '1:288094030368:ios:b57d8337b845b441494a45',
    messagingSenderId: '288094030368',
    projectId: 'todoapp-3f159',
    storageBucket: 'todoapp-3f159.appspot.com',
    iosClientId: '288094030368-mif4ontfvade2e2u5fprqvgpmq1h92cm.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoapp',
  );
}
